### ISSUE TITLE
missing mandatory ticket properties are not reported to the tracker

### ISSUE THREAD

**Issue by derpeter** [voc/publishing#30]
A missing propertie currently results in error that is not reportet back to tracker as script assumes it has no valid ticket. This is not optimal because there are many cases where a ticket is "valid enough" to report back the problem but noch still misses a propertie.

This will be fixed when the current "http upload" branch is merged back as some groudnwork to handle this kind of errors is already done there

**Comment by meise** [comment]
Another example:
<pre>
Traceback (most recent call last):
  File "./src/script_H_publishing.py", line 89, in __init__
    self.ticket = self._get_ticket_from_tracker()
  File "./src/script_H_publishing.py", line 159, in _get_ticket_from_tracker
    t = Ticket(tracker_ticket, ticket_id)
  File "/home/voc/publishing/src/model/ticket_module.py", line 53, in __init__
    self.abstract = self._validate_('Fahrplan.Abstract', True)
  File "/home/voc/publishing/src/model/ticket_module.py", line 118, in _validate_
    raise TicketException(key + ' is empty in ticket')
model.ticket_module.TicketException: Fahrplan.Abstract is empty in ticket

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./src/script_H_publishing.py", line 288, in <module>
    publisher = Publisher()
  File "./src/script_H_publishing.py", line 91, in __init__
    raise PublisherException('Could not get ticket from tracker') from e_
PublisherException: Could not get ticket from tracker
</pre>

**Comment by derpeter** [comment]
fixed in 34c3 release
